### ISSUE TITLE
FFmpeg SCTE-35 Stream Type

### ISSUE THREAD

**Issue by bbgdzxng1** [futzu/threefive#32]
futzu wrote.. _"I don't know how to stop ffmpeg from changing the SCTE35 stream type to 0x6."_

FYI - I did some experiments with this and it seems to be a limitation of FFmpeg's TS muxer.

If I use the NUT container (FFmpeg's proprietary container format), the `-tag:d` can be used to set the type.  In theory, this tag should also be capable of setting the type via a fourcc value, but that does not seem to be supported for data streams.  Hex or decimal work with a NUT container though.

In this case, the stream description was changed from `scte_35` to `none`.

```
$ ffmpeg -hide_banner -i "https://futzu.com/xaa.ts" -map 0:v:0 -codec:v copy -streamid 0:0x101 -map 0:a:0 -codec:a copy -streamid 1:0x102 -map 0:d:0 -codec:d:0 copy -streamid 2:0x103 -tag:d:0 "0x86" -f nut OUTFILE.nut -y

# or

$ ffmpeg -hide_banner -i "https://futzu.com/xaa.ts" -map 0:v:0 -codec:v copy -streamid 0:0x101 -map 0:a:0 -codec:a copy -streamid 1:0x102 -map 0:d:0 -codec:d:0 copy -streamid 2:0x103 -tag:d:0 "134" -f nut OUTFILE.nut -y

$ ffprobe OUTFILE.nut
  Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(tv, bt470bg), 544x576 [SAR 64:33 DAR 544:297], 50 fps, 50 tbr, 90k tbn, 50 tbc
  Stream #0:1(eng): Audio: mp2 (P[0][0][0] / 0x0050), 48000 Hz, stereo, s16p, 128 kb/s
  Stream #0:2: Data: none ([134][0][0][0] / 0x0086)
```

If the same command is used with an MPEG-TS container, the FFmpeg muxer overwrites the type to be 0x6.  At runtime / console output, it claims it is setting the 0x86, but when probed, the file output is 0x6.

In this case, the stream type was changed from `scte_35` to `bin_data`.

```
$ ffmpeg -hide_banner -i "https://futzu.com/xaa.ts" -map 0:v:0 -codec:v copy -streamid 0:0x101 -map 0:a:0 -codec:a copy -streamid 1:0x102 -map 0:d:0 -codec:d:0 copy -streamid 2:0x103 -tag:d:0 "0x86" -f mpegts OUTFILE.ts -y

$ ffprobe OUTFILE.ts
  Stream #0:0[0x101]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, top first), 544x576 [SAR 64:33 DAR 544:297], 25 fps, 50 tbr, 90k tbn, 50 tbc
  Stream #0:1[0x102](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:2[0x103]: Data: bin_data ([6][0][0][0] / 0x0006)
```

This is not an issue with threefive, it is purely informational and can be closed.  I recognize that threefive successfully works around FFmpeg's limitation.  Raising the ticket was just a means of sharing knowledge and narrowing down where FFmpeg was struggling.  Neither does the ticket solve the issue because the ultimate goal is setting it in a TS container, not a NUT container.  Feel free to close this issue.

**Comment by futzu** [comment]
```
-tag:d:0 "0x86"
```
So that's how it works...
I tried using -tag, but I didn't know how to specify the stream. 
I've never used the NUT container, I'm going to have to check it out. 

I've been contemplating adding some code to change 
a stream type in the PMT, that's where I get the stream type.

I don't know where the fourcc tag is stored in mpegts, that probably should set too though.  

I'm going to make this a discussion, because I just noticed there was a option to do that,
 and in hopes that you'll help me figure it out.



Have you ever played with mplex? 

[mplex13818-1.1.8.tar.gz](https://github.com/futzu/threefive/files/6887606/mplex13818-1.1.8.tar.gz)

The information is appreciated man,  post anytime you like. 

Adrian
